### PR TITLE
Added github oauth

### PR DESCRIPTION
**Pull request by arcticbarra**
Hi there!

I decided to implement GitHub Authentication. This solves https://github.com/brunoao86/rails-third-party-auth/issues/5

### CODE REVIEW

**Comment by brunoao86** [comment]
Hi, @arcticbarra!

Thanks for your contribution! I'll take a look at this tonight!

**Comment by brunoao86** [comment]
Thanks again for your contribution, @arcticbarra!

I've tested your implementation here and everything worked fine! I just had to make a little adjustment on `initializers/omniauth.rb`, adding `scope: 'user'` do get the email. Not a big deal.

I'm merging your right now! ✌️

**Comment by brunoao86** [comment]
Already deployed. ❤️ 

https://rails-third-party-auth.herokuapp.com/login

**Comment by arcticbarra** [comment]
Awesome!

**Pull request merged**
